<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Async, Await Error handling</title>
  </head>
  <body>
    <script>
      function wait(ms = 0) {
        return new Promise(resolve => {
          setTimeout(resolve, ms);
        });
      }
      //   console.log(wait);

      function makePizza(toppings = []) {
        return new Promise(function(resolve, reject) {
          // reject if people try with pineapple
          if (toppings.includes('pineapple')) {
            reject('Seriously? Get out pineapple');
          }
          const amountOfTimeToBake = 500 + toppings.length * 200;
          // wait 1 second for the pizza to cook
          setTimeout(function() {
            // when you are ready, you can resolve this promise
            resolve(
              `Here is your pizza with the toppings ${toppings.join(' ')} `
            );
          }, amountOfTimeToBake);
          // if something went wrong, we can reject the promise;
        });
      }

      // using try catch for catching errors

      //   async function go() {
      //     try {
      //       const pizza = await makePizza(['pineapple']);
      //       console.log(pizza);
      //     } catch (err) {
      //       console.log('Oh! noooo');

      //       console.log(err);
      //     }
      //   }

      // Another way to catch error in async function

      function handleError(err) {
        console.log('Ohhh noo!');
        console.log(err);
      }
      // when you marked function like "async", it return promise
      async function go() {
        const pizza = await makePizza(['pineapple']);
        console.log(pizza);
        return pizza;
      }
      // catch it at run time
      go().catch(handleError);
      // make a safe function with a HOF

      function makeSafe(fn, errorHandler) {
        return function() {
          fn().catch(errorHandler);
        };
      }
      const safeGo = makeSafe(go, handleError);
      safeGo();
    </script>
  </body>
</html>
